name: 'tauri'

on:
  push:
    paths-ignore:
      - '**.md'
      - 'daemon/**'
      - 'ui/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'daemon/**'
      - 'ui/**'

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, macos-15-intel, ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.1 libayatana-appindicator3-dev librsvg2-dev

      - name: install frontend dependencies
        working-directory: .
        run: |
          npm install -g pnpm
          npm install

      # draft tauri app
      - uses: tauri-apps/tauri-action@v0
        if: ${{ !startsWith(github.event.ref, 'refs/tags/') }}
        env:
          working-directory: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-draft
          releaseName: 'app-draft'
          releaseDraft: true
          prerelease: true

      # release tauri app
      - uses: tauri-apps/tauri-action@v0
        if: startsWith(github.event.ref, 'refs/tags/')
        env:
          working-directory: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'v__VERSION__'
          releaseDraft: true
          prerelease: true
